// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXnLScreZsm2UyRbvmi6JwiwJUZFaQa7w',
    appId: '1:840800333512:web:bdab7b8dab4242721efffd',
    messagingSenderId: '840800333512',
    projectId: 'eliteaircrew-app',
    authDomain: 'eliteaircrew-app.firebaseapp.com',
    storageBucket: 'eliteaircrew-app.firebasestorage.app',
    measurementId: 'G-G8WBD7F4NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Opyyc5gDOTl1Dz4eOGAI4U3-x7d_OQ8',
    appId: '1:840800333512:android:1e0f3b0be584f5ee1efffd',
    messagingSenderId: '840800333512',
    projectId: 'eliteaircrew-app',
    storageBucket: 'eliteaircrew-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnKQwN7gkJhqJLpNMcAF05NjkDkIUU0v8',
    appId: '1:840800333512:ios:5af32c5e1aa00ab31efffd',
    messagingSenderId: '840800333512',
    projectId: 'eliteaircrew-app',
    storageBucket: 'eliteaircrew-app.firebasestorage.app',
    iosBundleId: 'com.example.zxc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnKQwN7gkJhqJLpNMcAF05NjkDkIUU0v8',
    appId: '1:840800333512:ios:5af32c5e1aa00ab31efffd',
    messagingSenderId: '840800333512',
    projectId: 'eliteaircrew-app',
    storageBucket: 'eliteaircrew-app.firebasestorage.app',
    iosBundleId: 'com.example.zxc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXnLScreZsm2UyRbvmi6JwiwJUZFaQa7w',
    appId: '1:840800333512:web:afa68271583ba0e11efffd',
    messagingSenderId: '840800333512',
    projectId: 'eliteaircrew-app',
    authDomain: 'eliteaircrew-app.firebaseapp.com',
    storageBucket: 'eliteaircrew-app.firebasestorage.app',
    measurementId: 'G-QVKN6TMJDP',
  );
}
